apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xcodereview-dev

bases:
  - ../../base

commonLabels:
  environment: development

patchesStrategicMerge:
  - configmap.yaml

replicas:
  - name: xcodereview-backend
    count: 1

images:
  - name: xcodereview/backend
    newTag: dev-latest
