apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xcodereview-prod

bases:
  - ../../base

commonLabels:
  environment: production

patchesStrategicMerge:
  - configmap.yaml

replicas:
  - name: xcodereview-backend
    count: 3

images:
  - name: xcodereview/backend
    newTag: v2.0.0
